### PR TITLE
feat: Added support for country in lookup ⭐️

### PR DESCRIPTION
**Pull request by mmoriani**
Hi, in my case I couldn't find my app because it was only available in the Italian app store.
I added the possibility to specify the country when calling the "openStoreListing" function!

### CODE REVIEW

**Comment by riderx** [comment]
Hello @mmoriani thank you so much for the addition! That a great one !
Do the issue can happen in Android too?
if you can update the comment in the definition, that necessary for the auto generated doc

**Comment by riderx** [comment]
Thanks that perfect, can you pull from main to resolve conflict, then i merge it :)

**Comment by riderx** [comment]
also if you want the changelog to generate well your changes, you need to rename your commit by following https://www.conventionalcommits.org/en/v1.0.0/

**Comment by mmoriani** [comment]
I've resolved conficts!
Next time i'll follow conventional commits convention for new commits :)

**Pull request merged**
